[package]
name = "research-cell"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.0.2", features = ["sqlite"] }
dotenvy = "0.15.6"
rocket = { version = "0.5.0-rc.2", features = ["json"] }

